package com.seeds.yk;

import java.util.HashMap;
import java.util.Map;

import javax.sql.DataSource;

import org.apache.log4j.Logger;
import org.junit.Test;

import com.alibaba.druid.pool.DruidDataSource;

/**
 *
 */
public class DBMysql {

    private Logger log=Logger.getLogger(DBMysql.class);
    private DruidDataSource ds;
    public static SimpleQueryRunner runner;
	public static final DBMysql db = new DBMysql();
	
	
	static {
		new DBMysql();
	}
	
	public DBMysql() {
		initDataSource();
	}
	
	public void initDataSource() {
		String url ="jdbc:mysql://140.143.160.101:336699/hg?connectTimeout=10000&zerodatetimebehavior=converttonull&characterEncoding=utf8&useSSL=false";
		String userName = "root";
		String password ="";
		String drverClass = "com.mysql.jdbc.Driver";
		
		Map<String,Object> pp = new HashMap<String,Object>();
		pp.put("url",url);
		pp.put("username",userName);
		pp.put("passowrd", password);
		pp.put("driverClassName", drverClass);
		
		try {
			ds = new DruidDataSource();
			ds.setDriverClassName(drverClass);
			ds.setUrl(url);
			ds.setUsername(userName);
			ds.setPassword(password);
			runner = new SimpleQueryRunner(ds);
		} catch (Exception e) {
			e.printStackTrace();
			throw new RuntimeException(e);
		}
	}
	
	String createTable ="CREATE TABLE tbZJZ("
			  		+ " lId integer generated by default as identity ,"
			  		+ " nState integer ,"
			  		+ " strLinkName varchar(64),"
			  		+ " strLinkUrl varchar(1024),"
			  		+ " strMsg varchar(256),"
			  		+ " strDateTime varchar(32),"
			  		+ " primary key(lId) "
			  		+ " );";
	@Test
	public void print() {
		System.out.println(createTable);
	}
}
